### PR TITLE
Rust upgrade (1.0.0-nightly).

### PR DESCRIPTION
**Pull request by ArtemGr**
Changes necessary to build under the latest Rust nightly without errors and warnings.

### CODE REVIEW

**Comment by jeremyletang** [comment]
hi !

Thanks for the PR ! why the unstable flag is needed ?

**Comment by ArtemGr** [comment]
> why the unstable flag is needed ?

To avoid a ton of warnings.
Rust now emits a warning everywhere a non-stable API is used.

**Comment by jeremyletang** [comment]
oh, yes sure , but I was thinking that only `int` will produce these warning, but you changes them.
Anyway, I'll merge this ! thank's !

**Comment by ArtemGr** [comment]
You might want to allow unstable warnings when you, say, decide to rewrite the library in the stable subset of the APIs.

**Pull request merged**
